---
spring:
  profiles: sentence
eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It
eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: article
words: a,the
eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  
eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
